import {
  collection,
  doc,
  onSnapshot,
  orderBy,
  query,
} from "firebase/firestore";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import { useRecoilState } from "recoil";
import { modalState } from "../atoms/modatAtom";
import { getProviders, getSession, useSession } from "next-auth/react";
import Login from "../components/Login";
import Modal from "../components/Modal";
import Sidebar from "../components/Sidebar";
import Widgets from "../components/Widgets";
import { db } from "../firebase";
import { ArrowLeftIcon } from "@heroicons/react/outline";
import Post from "../components/Post";
import Comment from "../components/Comment";

function Postpage({ trendingresults, followresults, providers }) {
  const { data: session } = useSession();
  const [isOpen, setIsOpen] = useRecoilState(modalState);
  const [post, setPost] = useState();
  const router = useRouter();
  const [comments, setComments] = useState([]);
  const { id } = router.query;

  useEffect(() => {
    onSnapshot(doc(db, "posts", id), (snapshot) => {
      setPost(snapshot.data());
    }),
      [db];
  });
  useEffect(
    () =>
      onSnapshot(
        collection(db, "posts", id, "comments"),
        orderBy("timestamp", "desc"),
        (snapshot) => {
          setComments(snapshot.docs);
        }
      ),
    [db, id]
  );

  if (!session) return <Login providers={providers} />;

  return (
    <div>
      <Head>
        <title>
          {post?.username} on Twitter: {post?.text}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-black min-h-screen max-w-[1500px] mx-auto flex">
        <Sidebar />
        <div className="text-white flex-grow border-l border-r border-gray-700 max-w-[900px] lg:max-w-[600px] sm:ml-[73px]  xl:ml-[370px] xl:max-w-[900px]">
          <div className="flex items-center px-1.5 py-2 border-b border-gray-700 text-[#d9d9d9] font-semibold text-xl gap-x-4 sticky top-0 z-50 bg-black">
            <div
              className="hoverAnimation w-9 h-9 flex items-center justify-center xl:px-0"
              onClick={() => router.push("/")}
            >
              <ArrowLeftIcon className="h-5 text-white" />
            </div>
            Tweet
          </div>
          <Post id={id} post={post} Postpage />
          {comments.length > 0 && (
            <div className="pb-72">
              {comments.map((comment) => (
                <Comment
                  key={comment.id}
                  id={comment.id}
                  comment={comment.data()}
                />
              ))}
            </div>
          )}
        </div>
        <Widgets
          trendingresults={trendingresults}
          followresults={followresults}
        />
        {isOpen && <Modal />}
      </main>
    </div>
  );
}

export default Postpage;
export const getServerSideProps = async (ctx) => {
  const trendingresults = await fetch("https://jsonkeeper.com/b/NKEV").then(
    (res) => res.json()
  );
  const followresults = await fetch("https://jsonkeeper.com/b/WWMJ").then(
    (res) => res.json()
  );
  const providers = await getProviders();
  const session = await getSession(ctx);
  return {
    props: {
      trendingresults,
      followresults,
      providers,
      session,
    },
  };
};
